{
 "title": "Livepeer Payments Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "# Tickets Sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(livepeer_tickets_sent)" }
   ]
  },
  {
   "title": "Avg Tickets Sent Per Sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(livepeer_tickets_sent[5m]))"
    }
   ]
  },
  {
   "title": "Ticket Value (EV) Sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(livepeer_ticket_value_sent / 1e9)"
    }
   ]
  },
  {
   "title": "Avg Ticket Value Sent Per Sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(livepeer_ticket_value_sent[5m])) / 1e9"
    }
   ]
  },
  {
   "title": "Million Pixels Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(livepeer_mil_pixels_processed)"
    }
   ]
  },
  {
   "title": "Million Pixels Processed Per Sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(livepeer_mil_pixels_processed[5m]))"
    }
   ]
  },
  {
   "title": "# Tickets Received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "sum(livepeer_tickets_recv)" }
   ]
  },
  {
   "title": "Avg Tickets Received Per Sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(livepeer_tickets_recv[5m]))"
    }
   ]
  },
  {
   "title": "Ticket Value (EV) Received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(livepeer_ticket_value_recv / 1e9)"
    }
   ]
  },
  {
   "title": "Avg Ticket Value Received Per Sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(livepeer_ticket_value_recv[5m])) / 1e9"
    }
   ]
  },
  {
   "title": "Avg Price Per Pixel Sent Per Sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(sum(rate(livepeer_ticket_value_sent[5m])) * 1e9) / (sum(rate(livepeer_mil_pixels_processed[5m])) * 1000000)"
    }
   ]
  },
  {
   "title": "Avg Price Per Pixel Recv Per Sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "(sum(rate(livepeer_ticket_value_recv[5m])) * 1e9) / (sum(rate(livepeer_mil_pixels_processed[5m])) * 1000000)"
    }
   ]
  },
  {
   "title": "# Winning Tickets Received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(livepeer_winning_tickets_recv)"
    }
   ]
  },
  {
   "title": "Value Redeemed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(livepeer_value_redeemed / 1e9)"
    }
   ]
  },
  {
   "title": "Suggested Gas Price",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "ETH (gwei)" }
   ],
   "targets": [
    { "expr": "livepeer_suggested_gas_price" }
   ]
  },
  {
   "title": "Transcoding Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "ETH (wei)" }
   ],
   "targets": [
    { "expr": "livepeer_transcoding_price" }
   ]
  },
  {
   "title": "Payment Receive Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    { "expr": "livepeer_payment_recv_errors" }
   ]
  },
  {
   "title": "Payment Creation Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    { "expr": "livepeer_payment_create_errors" }
   ]
  },
  {
   "title": "Ticket Redemption Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    {
     "expr": "livepeer_ticket_redemption_errors"
    }
   ]
  }
 ]
}