name: geth-with-protocol
on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          config: .github/buildkitd.toml

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./geth-with-protocol
          platforms: linux/arm64, linux/amd64
          push: true
          tags: livepeer/geth-with-livepeer-protocol:confluence
